from fastapi import FastAPI
from pydantic import BaseModel
from . import query_engine 
class QueryRequest(BaseModel):
    question: str

app = FastAPI(
    title="CareerPath AI API",
    description="API for the intelligent career path agent.",
    version="0.1.0",
)

@app.get("/")
def read_root():
    return {"message": "Welcome to the CareerPath AI API"}

@app.post("/query")
def run_query(request: QueryRequest):
    """
    Receives a question and returns the response generated by the RAG system.
    """
    response_text = query_engine.get_rag_response(query=request.question)
    return {"answer": response_text}